spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test-db

config:
  aes256:
    algorithm: AES/CBC/PKCS5Padding
    key: saieialijfliejlk
  registrable:
    names:
      - ???
      - ???
      - ???
      - ???
      - ???
    reg-nos:
      - 860824-1655068
      - 921108-1582816
      - 880601-2455116
      - 910411-1656116
      - 820326-2715702