ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]

= Pay Here API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

[[Auth]]
== 계정

[[Auth-sign-up]]
=== 회원 가입

operation::auth/sign-up[snippets='http-request,request-fields,http-response,response-fields']

[[Auth-sign-in]]
=== 로그인

operation::auth/sign-in[snippets='http-request,request-fields,http-response,response-fields']

[[Auth-sign-out]]
=== 로그아웃

operation::auth/sign-out[snippets='http-request,http-response,response-fields']

[[Auth-me]]
=== 내 정보

operation::auth/me[snippets='http-response,response-fields']

[[Account-Book]]
== 가계부

[[Account-Book-find-one]]
=== 단일 조회

operation::account-book/find-one[snippets='http-request,path-parameters,http-response,response-fields']

[[Account-Book-find-all]]
=== 목록 조회

operation::account-book/find-all[snippets='http-request,http-response,response-fields']

[[Account-Book-create]]
=== 생성

operation::account-book/create[snippets='http-request,request-fields,http-response,response-fields']

[[Account-Book-update]]
=== 수정

operation::account-book/update[snippets='http-request,path-parameters,request-fields,path-parameters,http-response,response-fields']

[[Account-Book-delete-one]]
=== 삭제

operation::account-book/delete-one[snippets='http-request,path-parameters,http-response,response-fields']

[[Account-Book-restore-all]]
=== 전체 복구

operation::account-book/restore-all[snippets='http-request,http-response,response-fields']