version: '3.8'

services:
  database:
    container_name: database
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=payhere
      - MYSQL_USER=payhere
      - MYSQL_PASSWORD=payhere
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/volume:/var/lib/mysql
    networks:
      - payhere-network

  server:
    restart: always
    container_name: server
    platform: linux/amd64
    image: azqazq195/payhere:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/payhere
      SPRING_DATASOURCE_USERNAME: payhere
      SPRING_DATASOURCE_PASSWORD: payhere
    networks:
      - payhere-network

networks:
  payhere-network:
    driver: bridge